#!/bin/bash

stop(){
    sudo ip link set wlan0 down
    sudo iwconfig wlan0 mode managed
    sudo ip link set wlan0 up
    sudo service NetworkManager start
    iwconfig wlan0 | grep Mode | awk '{print $1}'
}

start(){
    sudo ip link set wlan0 down
    sudo iwconfig wlan0 mode monitor
    sudo ip link set wlan0 up
    iwconfig wlan0 | grep Mode | awk '{print $1}'
}

case $1 in 
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: monitor (start | stop)"
esac

